// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UMBIT.Precatorios.Infraestrutura.Contextos;

#nullable disable

namespace UMBIT.Precatorios.API.Migrations
{
    [DbContext(typeof(AppContexto))]
    [Migration("20241107212344_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UMBIT.Precatorios.Dominio.Entidades.auth.Permissao.VinculoDePermissaoUsuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("char(36)");

                    b.Property<string>("Api")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TipoPermissao")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("IdentificadorDePermissao")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.HasKey("IdUsuario", "Api", "TipoPermissao", "IdentificadorDePermissao");

                    b.ToTable("VinculoDePermissaoUsuario");
                });

            modelBuilder.Entity("UMBIT.Precatorios.Dominio.Entidades.auth.Token.ApiToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ApiSecret")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("ExpiresMins")
                        .HasColumnType("double");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("char(36)");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Kid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ApiToken");
                });

            modelBuilder.Entity("UMBIT.Precatorios.Dominio.Entidades.judicial.gerenciamento.VinculoDeGerenciamentoProcesso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Uuid");

                    b.ToTable("VinculoDeGerenciamentoProcesso");
                });
#pragma warning restore 612, 618
        }
    }
}
