//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.7.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable CS8765 // Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes).

namespace UMBIT.Precatorios.Contrato.Autenticacao
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.0.7.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]

    public abstract class AutenticacaoControllerBase : UMBIT.Precatorios.SDK.API.Controllers.BaseController
    {
        protected AutenticacaoControllerBase(System.IServiceProvider serviceProvider) : base(serviceProvider)
        {
        }

        /// <remarks>
        /// Login de usuario
        /// </remarks>
        /// <returns>Success</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("login")]
        public abstract System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<TokenResponse>> Login([Microsoft.AspNetCore.Mvc.FromBody] Login body);

        /// <remarks>
        /// Logout de usuario
        /// </remarks>
        /// <returns>Success</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("logout")]
        public abstract System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.IActionResult> Logout();

        /// <returns>Success</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("login/twofactor")]
        public abstract System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<TokenResponse>> Twofactor([Microsoft.AspNetCore.Mvc.FromBody] TwoFactorRequest body);

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.7.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Login
    {

        [System.Text.Json.Serialization.JsonPropertyName("user")]
        public string User { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("password")]
        public string Password { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("audience")]
        public string Audience { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.7.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TwoFactorRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("audience")]
        public string Audience { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("twoFactorCode")]
        public string TwoFactorCode { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("email")]
        public string Email { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.7.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TokenResponse : Resposta
    {

        [System.Text.Json.Serialization.JsonPropertyName("dados")]
        public Dados Dados { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.7.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Resposta
    {

        [System.Text.Json.Serialization.JsonPropertyName("sucesso")]
        public bool Sucesso { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("erros")]
        public System.Collections.Generic.List<Erros> Erros { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("errosSistema")]
        public System.Collections.Generic.List<ErrosSistema> ErrosSistema { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.7.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Dados
    {

        [System.Text.Json.Serialization.JsonPropertyName("enabledTwoFactor")]
        public bool EnabledTwoFactor { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("accessToken")]
        public string AccessToken { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("refreshToken")]
        public string RefreshToken { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("expiresIn")]
        public int ExpiresIn { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("usuarioToken")]
        public UsuarioToken UsuarioToken { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.7.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Erros
    {

        [System.Text.Json.Serialization.JsonPropertyName("titulo")]
        public string Titulo { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("mensagem")]
        public string Mensagem { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.7.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ErrosSistema
    {

        [System.Text.Json.Serialization.JsonPropertyName("excecao")]
        public string Excecao { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("excecaoInterna")]
        public string ExcecaoInterna { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("rastreamentoPilha")]
        public string RastreamentoPilha { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("metodoCodigoFonte")]
        public string MetodoCodigoFonte { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("nomeArquivoFonte")]
        public string NomeArquivoFonte { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("LinhaCodigoFonte")]
        public double LinhaCodigoFonte { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("ObjetoManipulado")]
        public object ObjetoManipulado { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.7.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UsuarioToken
    {

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string Id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("Nome")]
        public string Nome { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("claims")]
        public System.Collections.Generic.List<Claims> Claims { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.7.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Claims
    {

        [System.Text.Json.Serialization.JsonPropertyName("value")]
        public string Value { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        public string Type { get; set; }

    }


}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625