//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.7.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface Login {
    user: string;
    password: string;
    audience: string;
}

export interface TwoFactorRequest {
    audience: string | undefined;
    twoFactorCode: string | undefined;
    email: string | undefined;
}

export interface Resposta {
    sucesso: boolean;
    erros: Erros[];
    errosSistema: ErrosSistema[];
}

export interface TokenResponse extends Resposta {
    dados: Dados;
}

export interface Dados {
    enabledTwoFactor: boolean;
    accessToken: string;
    refreshToken: string;
    expiresIn: number;
    usuarioToken: UsuarioToken;
}

export interface Erros {
    titulo: string;
    mensagem: string;
}

export interface ErrosSistema {
    excecao: string;
    excecaoInterna: string;
    rastreamentoPilha: string;
    metodoCodigoFonte: string;
    nomeArquivoFonte: string;
    LinhaCodigoFonte: number;
    ObjetoManipulado: any;
}

export interface UsuarioToken {
    id: string;
    Nome: string;
    claims: Claims[];
}

export interface Claims {
    value: string;
    type: string;
}