//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.7.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface ForgotPasswordRequest {
    email: string | undefined;
}

export interface RegisterRequest {
    email: string | undefined;
    password: string | undefined;
    name: string | undefined;
    fotoData: string | undefined;
    dataNascimeto: Date;
}

export interface ResendConfirmationEmailRequest {
    email: string | undefined;
}

export interface ResetPasswordRequest {
    email: string | undefined;
    resetCode: string | undefined;
    newPassword: string | undefined;
}