//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.7.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface ProcessoDTO {
    id: string;
    numeroProcesso: string;
    classe: string;
    nome: string;
    assunto: string;
    valor: string;
    serventia: string;

    [key: string]: any;
}

export interface VinculosGerenciamentoProcessoDTO {
    uuid: string;
    status: number;

    [key: string]: any;
}

export interface CriarVinculosGerenciamentoProcessoRequest {
    uuids: string[];

    [key: string]: any;
}